# Generated by Django 5.2.3 on 2025-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
